Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@andrewgwardwell 
edx
/
frontend-component-footer-edx
Public
Code
Issues
1
Pull requests
10
Actions
Wiki
Security
Insights
frontend-component-footer-edx/.github/workflows/manual-publish.yml
@adamstankiewicz
adamstankiewicz chore: auth with npm before publish
Latest commit edee922 16 hours ago
 History
 1 contributor
40 lines (40 sloc)  1.23 KB

name: Manual Publish
on: [workflow_dispatch]
jobs:
  release:
    name: Manual Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Validate package-lock.json changes
      run: make validate-no-uncommitted-package-lock-changes
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test
    - name: i18n_extract
      run: npm run i18n_extract
    - name: Coverage
      uses: codecov/codecov-action@v2
    - name: Build
      run: npm run build
    # NPM expects to be authenticated for publishing. This step will fail CI if NPM is not authenticated
    - name: Check NPM authentication
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}" >> .npmrc
        npm whoami
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_NPM_TOKEN }}
      # `npm publish` relies on version specified in package.json file
      run: npm publish --tag old-version
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
frontend-component-footer-edx/manual-publish.yml at v4.6.2 · edx/frontend-component-footer-edx